# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2eb96828ea72045b9150e6152ee75d5838b0f67f4320a326a9d45c741ca9a955380a62b0792eba871a1312d2fb1468929028aa7923bbd063ecc072d0a73d6a37

test:
  secret_key_base: 2c76cd388ec86661d767b4beed37caa08fcd7f47cb1ef23084dd6d5d38fc23c4b4ed626bf7ddc2593e9db8c65ae8d195052865da74918611a0728cde49051283

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
